### ISSUE TITLE
Monolith tints not displaying

### ISSUE THREAD

**Issue by Zer0Info** [487666123/ImproveGame#72] opened 2024-03-13 20:31 UTC
Hi! Whenever I have this mod enabled, any screen overlays, such as the blue tint from the stardust monolith, do not seem to display unless the game is paused? Not sure why, as I have no other mods enabled. Thank you for your time.

**Comment by ghost** [comment] 2024-03-19 18:12
Same issue. Doesn't works with any effects that can be caused by the monoliths like blood moon or even modded ones like from the Catalyst mod or the Wrath of the Gods.

**Comment by ghost** [comment] 2024-03-19 18:16
Also, if you switch the monolith, screen filter works for some time untill it fully loads.

**Comment by Cyrillya** [comment] 2024-04-04 15:15
Can you offer your world files? (both `.wld` and `.twld`)
And what version is the mod you are using?

**Comment by ghost** [comment] 2024-04-04 16:05
Happens in any world no matter what mods are enabled either while the bug is happening or when the world was generated. Latest version of mod and tmodloader. Not sure if the bug existed before 1.7.0.0 update.

**Comment by ghost** [comment] 2024-04-04 16:07
[Worlds.zip](https://github.com/487666123/ImproveGame/files/14874011/Worlds.zip) world files if it somehow depends on the system.

**Comment by Cyrillya** [comment] 2024-04-04 16:55
> Happens in any world no matter what mods are enabled either while the bug is happening or when the world was generated. Latest version of mod and tmodloader. Not sure if the bug existed before 1.7.0.0 update.

Didn't happen on my end so that's kinda annoying
If you've turned on Glassmorphism Effect, turn it off and try again

**Comment by ghost** [comment] 2024-04-04 16:59
Yea, it was it. Setting it to off solved the issue.

**Comment by Cyrillya** [comment] 2024-04-04 17:20
I'll update the mod these days and try to fix the issue. You can test them when the update is published

**Comment by Cyrillya** [comment] 2024-04-06 00:06
Updated. Try again now

**Comment by ghost** [comment] 2024-04-06 00:11
Fixed now, thanks.

**Closed as completed** 2024-04-06 00:58 UTC
Labels: bug, priority: low
